stages:
  - build
  - publish

variables:
  VERSION: "0.0.0-development"

build:
  stage: build
  script:
    - cd src/J2NET
    - dotnet pack --configuration Release -p:Version=$VERSION -o "../../artifacts"
  artifacts:
    paths:
      - artifacts
  tags:
    - windows
    
publish_nuget:
  stage: publish
  script:
    - echo "Pushing J2NET version $VERSION"
    - dotnet nuget push "artifacts/DATPROF.J2NET.$VERSION.nupkg" --api-key "$NUGET_API_KEY" --source "$NEXUS_URL" --no-symbols
  when: manual
  tags:
    - windows  