name: Release J2NET
run-name: Release J2NET Runtimes ${{ inputs.VERSION }}

on:
  workflow_dispatch:
    inputs:
      VERSION:
        description: Version (ex. 1.3.0)

jobs:
  release:
    name: Release J2NET
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true

      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '7.0.x'

      - name: Build & Push
        shell: bash
        run: ./buildRuntimes.sh ${{ inputs.VERSION }} --push ${{ vars.J2NET_NUGET_SOURCE }} ${{ secrets.J2NET_NUGET_API_KEY }}
